spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://b86e825d36a77c:03e55f27@eu-cdbr-west-01.cleardb.com/heroku_0e9ff4d58e25f1f?reconnect=true
    username: 03e55f27
    password: b86e825d36a77c

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${PORT:8080}

spring.mail:
  host: smtp.mail.ru
  username: contact@megoru.ru
  password: BxKY2YVj#dpCb#G
  port: 465

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 800 55-35-35
  email: blog@gmail.com
  copyright: Савин Юрий
  copyrightFrom: 2021
